apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ping-prober
  name: ping-prober-cm
  namespace: kube-admin
data:
  config.prod.yaml: |-
    consul:
      address: MyConsul:8500
      scheme: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-probe
  namespace: kube-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-prober
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: ping-prober
        cluster: MyCluster
        account: MyAccount
        region: MyRegion
        vpc: MyVpc
    spec:
      hostNetwork: true
      containers:
      - image: knsdnet/ping-exporter:v0.3.1
        name: ping-exporter
        ports:
        - containerPort: 9346
        resources:
          limits:
            cpu: 256m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 512Mi
        livenessProbe:
          httpGet:
            port: 9346
            path: /metrics
        imagePullPolicy: IfNotPresent
      - image: zbd20/ping-probe-register:v0.0.1
        name: ping-probe
        volumeMounts:
          - mountPath: /etc/config
            name: config
        ports:
        - containerPort: 9347
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: REGION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['region']
        - name: VPC
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['vpc']
        - name: ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['account']
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            port: 9347
            path: /
        imagePullPolicy: IfNotPresent
      volumes:
        - name: config
          configMap:
            name: ping-prober-cm
