{
 "title": "Ping网络质量",
 "description": "ping monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(up{app=\"ping-monitor\"},job)"
    }
   },
   { "name": "app", "query": "ping-monitor" },
   {
    "name": "source_region",
    "query": {
     "query": "label_values(up{app=\"$app\"},source_region)"
    }
   },
   {
    "name": "source_vpc",
    "query": {
     "query": "label_values(up{app=\"$app\",source_region=\"$source_region\"},source_vpc)"
    }
   },
   {
    "name": "target_region",
    "query": {
     "query": "label_values(up{app=\"$app\"},target_region)"
    }
   },
   {
    "name": "target_vpc",
    "query": {
     "query": "label_values(up{app=\"$app\",target_region=\"$target_region\"},target_vpc)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "探针总数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(up{app=\"ping-monitor\"}) by (job))"
    }
   ]
  },
  {
   "title": "探针数 AWS/ap-southeast-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(up{app=\"ping-monitor\",source_region=\"ap-southeast-1\"}) by (job))"
    }
   ]
  },
  {
   "title": "探针数 AWS/us-east-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(up{app=\"ping-monitor\",source_region=\"us-east-1\"}) by (job))"
    }
   ]
  },
  {
   "title": "丢包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ping_packets_failed{job=~\"$job\",source_region=~\"$source_region\",source_vpc=~\"$source_vpc\",target_region=~\"$target_region\",target_vpc=~\"$target_vpc\"}",
     "legendFormat": "{{source_region}} {{source_vpc}} --> {{target_region}} {{target_vpc}}"
    }
   ]
  },
  {
   "title": "探针数 HW/ap-southeast-3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(up{app=\"ping-monitor\",source_region=\"ap-southeast-3\"}) by (job))"
    }
   ]
  },
  {
   "title": "延时 P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,ping_times_bucket{job=~\"$job\",source_region=~\"$source_region\",source_vpc=~\"$source_vpc\",target_region=~\"$target_region\",target_vpc=~\"$target_vpc\"})",
     "legendFormat": "{{source_region}} {{source_vpc}} --> {{target_region}} {{target_vpc}}"
    }
   ]
  },
  {
   "title": "丢包率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ping_packets_loss{job=~\"$job\",source_region=~\"$source_region\",source_vpc=~\"$source_vpc\",target_region=~\"$target_region\",target_vpc=~\"$target_vpc\"}",
     "legendFormat": "{{source_region}} {{source_vpc}} --> {{target_region}} {{target_vpc}}"
    }
   ]
  },
  {
   "title": "区域间平均延迟",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,ping_times_bucket{source_region=\"ap-southeast-1\",target_region=\"ap-southeast-3\"}))"
    },
    {
     "expr": "avg(histogram_quantile(0.99,ping_times_bucket{source_region=\"ap-southeast-3\",target_region=\"ap-southeast-1\"}))"
    },
    {
     "expr": "avg(histogram_quantile(0.99,ping_times_bucket{source_region=\"ap-southeast-3\",target_region=\"us-east-1\"}))"
    },
    {
     "expr": "avg(histogram_quantile(0.99,ping_times_bucket{source_region=\"us-east-1\",target_region=\"ap-southeast-3\"}))"
    },
    {
     "expr": "avg(histogram_quantile(0.99,ping_times_bucket{source_region=\"us-east-1\",target_region=\"ap-southeast-1\"}))"
    },
    {
     "expr": "avg(histogram_quantile(0.99,ping_times_bucket{source_region=\"ap-southeast-1\",target_region=\"us-east-1\"}))"
    }
   ]
  }
 ]
}